# You might ask, "Why use docker-compose if there's only 1 service?".  Totally valid question
# we're future-proofing here a bit because we know there are more services to come.

version: "3.9"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      # 3306 already bound to local mysql running on most SQ dev machines
      - "3307:3306"
    environment:
      # specifies the password that will be set for the MySQL root superuser account
      - MYSQL_ROOT_PASSWORD=tbdev
      # specifies the name of a database to be created on image startup
      - MYSQL_DATABASE=tbdex
    networks:
      tbdex:
        aliases:
          - "mysql"
    volumes:
      - ./src/main/resources/migrations:/docker-entrypoint-initdb.d
networks:
  tbdex:

